### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by oxinabox** [invenia/Hyperparameters.jl#9]
I wonder if we want to support default values for if the hyper-parameter is not provided?
`hyperparam(:foo, "1.5")` and `hyperparam(Int, :foo, "1")`

We would still have those recorded into the list of all hyperparameters.

If we wanted to get fancy we could allow those to be given as julia values (rather than strings),
and then use them to to decide what type to parse the enviroment variable as, if it is present

**Comment by samuel-massinon** [comment]
The problem I see here is that SageMaker would not know the value of parameter when hyperopting with regards with warm starting. A change in this value could cause tuning to be off.

**Comment by oxinabox** [comment]
Ah fair point. Probably lets not do this then
Sagemaker gets mad when you change the hyperparameters that it is aware  of during warm starting
